### ISSUE TITLE
[Bug]: Watch-video-playlist does not update as additions/removals are made to playlist

### ISSUE THREAD

**Issue by kommunarr** [PikachuEXE/FreeTube#56]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

Case 1: Adding videos
1. Create a playlist with three videos.
2. Open a video of that playlist from the Playlist tab.
3. Add a video from the Recommended Videos, or the current video, to the current playlist using the + "Add to playlist" button.
4. See that the watch-video-area does not update to include the videos added.

Case 2: Removing videos
The same issue also occurs for videos that are removed in another tab. To replicate:
1. Create a playlist with three videos.
2. Open a video of that playlist from the Playlist tab.
3. Open another tab and navigate the Playlist tab.
4. Open that playlist in the playlist tab.
5. Remove a video from the playlist.
6. Switch back to the first tab; notice that the video is still present in the watch-video-playlist.

### Expected Behavior

For Case 1, added videos to the playlist should automatically be added to the watch-video-playlist box (regardless of which tab the "Add" was initiated from.

For Case 2, removed videos from the playlist should automatically be removed from the watch-video-playlist box, regardless of which tab the "Remove" was initiated from. The edge case of the currently open video being removed is a unique one; in this one case, I think the removal should not be visibly reflected in the watch-video-playlist box until the route changes.

### Issue Labels

visual bug

### FreeTube Version

402af7a2f885aed8e72c808aca844c97bff8a3f7

### Operating System Version

OpenSUSE Tumbleweed

### Installation Method

other

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@jasonhenriquez i would recommend link the commit when filling in the FT version.

I know this is just Pikachu's repo so it doesn't matter that much but sometimes pikachu asked me if I'm using latest commit pushed to the branch because the thing i reported was already fixed.

So TLDR including commit you're using will remove confusion of what version you're using and time doenst have to be wasted by pika asking the question and u answering it

**Comment by PikachuEXE** [comment]
Tried a fix in 125a46741e46692ae3f2f03f45210fdd39375990

But I think there would still be a lot of related issues regard this

I understand the add/reorder one
But not removing item when it's being played with my implementation can lead to
- Remove current playing entry => playlist not updated
- Remove non current playing entry => new list of video entries still has no current entry => still cannot update the view

**Comment by kommunarr** [comment]
Removing the item unconditionally is fine if necessary, as long as the `watch-video-playlist` box is still visible.

Case 1 and 2 are still occurring locally on [25a467](https://github.com/PikachuEXE/FreeTube/commit/125a46741e46692ae3f2f03f45210fdd39375990).

**Comment by PikachuEXE** [comment]
I am not sure what's the best
But I would like to revisit this later

**Comment by PikachuEXE** [comment]
Updated in https://github.com/PikachuEXE/FreeTube/commit/7863d037ff59dc8dc715bbae56c3b17cd4d297a3

Currently playing video entry is removed anyway
Video index `0 / N`, progress bar empty
Play next = play first video
Play prev = play last video

Don't want too many exceptions handling code

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
LGTM, Based on the expected behavior Jason laid out.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@jasonhenriquez @jasonhenriquez @jasonhenriquez @jasonhenriquez @jasonhenriquez @jasonhenriquez @jasonhenriquez

**Comment by kommunarr** [comment]
ya, looks good
